/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Reward = IDL.Record({
  'name' : IDL.Text,
  'rank' : IDL.Opt(IDL.Nat),
  'score' : IDL.Nat,
});
export const LeaderboardEntry = IDL.Record({
  'name' : IDL.Text,
  'score' : IDL.Nat,
});

export const idlService = IDL.Service({
  'claimReward' : IDL.Func([IDL.Nat], [IDL.Opt(Reward)], ['query']),
  'getTopScores' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'submitScore' : IDL.Func([IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Reward = IDL.Record({
    'name' : IDL.Text,
    'rank' : IDL.Opt(IDL.Nat),
    'score' : IDL.Nat,
  });
  const LeaderboardEntry = IDL.Record({ 'name' : IDL.Text, 'score' : IDL.Nat });
  
  return IDL.Service({
    'claimReward' : IDL.Func([IDL.Nat], [IDL.Opt(Reward)], ['query']),
    'getTopScores' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'submitScore' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };